//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Buisness.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetInfo
    {
        public string LotName { get; set; }
        public string Username { get; set; }
        public int BetValue { get; set; }
        public System.DateTime BetDate { get; set; }
        public int ID { get; set; }
        public int UserID { get; set; }
        public int LotID { get; set; }
    }
}
