//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Buisness.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.UserDatas = new HashSet<UserData>();
        }
    
        public int ID { get; set; }
        public string LocationName { get; set; }
    
        public virtual ICollection<UserData> UserDatas { get; set; }
    }
}
