//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Buisness.Data
{
    using System;
    
    public partial class SearchByLotName_Result3
    {
        public int ID { get; set; }
        public string LotName { get; set; }
        public string Description { get; set; }
        public long StartCurrency { get; set; }
        public System.DateTime ActualDate { get; set; }
        public bool IsDeleted { get; set; }
        public int OwnerId { get; set; }
        public string ViewCount { get; set; }
        public int LotTypeID { get; set; }
    }
}
