//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Buisness.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.LotsSubCategories = new HashSet<LotsSubCategory>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string SubCategoryName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<LotsSubCategory> LotsSubCategories { get; set; }
    }
}
