//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Buisness.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Bets = new HashSet<Bet>();
            this.Bookmarks = new HashSet<Bookmark>();
            this.Comments = new HashSet<Comment>();
            this.Lots = new HashSet<Lot>();
            this.UserDatas = new HashSet<UserData>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public bool IsApproved { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual ICollection<Bet> Bets { get; set; }
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Lot> Lots { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserData> UserDatas { get; set; }
    }
}
