//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAuction.Buisness.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int ID { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int LocationID { get; set; }
        public Nullable<System.DateTime> BrithDate { get; set; }
        public string PhotoLink { get; set; }
        public int User_ID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
